name: terraform called workflow

on:
  workflow_call:
    inputs:
      DOMAIN:
        type: string
        description: 'target domain'
        required: true
    secrets:
      ENV: 
        required: true
        
env:
  APP: ${{ secrets.APP_PRIVATE_KEY }}
  eep: ${{ secrets.ENV}}
  XXX: ${{ inputs.DOMAIN == 'dlmz' && './' || vars.WRK_DIR  }}


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: | 
          echo "context"
          echo "${{ toJSON(github) }}"
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{env.XXX}}/${{inputs.DOMAIN}}/test

      - name: remove
        run: |
          rm -f ${{env.XXX}}/${{inputs.DOMAIN}}/test
          ls ${{env.XXX}}/${{inputs.DOMAIN}}/
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{env.XXX}}/${{inputs.DOMAIN}}/
          
      - name: test
        run: |
          ls ${{env.XXX}}/${{inputs.DOMAIN}}/

