name: terraform called workflow

on:
  workflow_call:
    inputs:
      DOMAIN:
        type: string
        description: 'target domain'
        required: true
env:
  APP: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: | 
          echo ${{inputs.DOMAIN}}
          echo ${{ vars.ID_DEV_DMLZ }}
          echo ${{ env.APP }}
