name: terraform called workflow

on:
  workflow_call:
    inputs:
      DOMAIN:
        type: string
        description: 'target domain'
        required: true
    secrets:
      ENV: 
        required: true
        
env:
  APP: ${{ secrets.APP_PRIVATE_KEY }}
  eep: ${{ secrets.ENV}}
  XXX: ${{ inputs.DOMAIN == 'dlmz' && '' || vars.WRK_DIR }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: | 
          echo ${{ env.XXX}}
          pwd
          ls
          cd ${{env.XXX}}/${{inputs.DOMAIN}}
          pwd
          echo ${{inputs.DOMAIN}}
          echo ${{ vars.ID_DEV_DMLZ }}
          echo ${{ env.APP }}
          echo ${{ env.eep}}
