name: create PR
on: [workflow_dispatch]
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: print env
       run: printenv
     - name: create pull request
       run: gh pr create -B main -H ${{ env.GITHUB_REF_NAME }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
       env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
