name: create PR
on:
  - workflow_dispatch
  - push:
      branches:
        - feature2
        - test
jobs:
  createPR:
    if: "contains(github.event.head_commit.message, 'createPR')"
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: print env
       run: printenv
     - name: create pull request
       run: gh pr create -B main -H $GITHUB_REF_NAME --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action' -r andrzejp1212 -a andrzejp1212
       env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
