name: create PR
on:
  push:
    branches:
        - feature2
        - test
jobs:
  createPR:
    if: "contains(github.event.head_commit.message, 'createPR')"
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: print env
       run: printenv
     - name: create pull request
       run: gh pr create -B main -H $GITHUB_REF_NAME --title 'Merge '$GITHUB_REF_NAME' into main' --body 'Created by Github action' -r andrzejp12-kodekloud/team-a
       env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
