on:
  pull_request:
    branches: 
      - main
    types: [created]

jobs:
  change-on-prod:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: push-prod
       run: |
         echo "branch: $GITHUB_REF_NAME"
         echo "doing something on STAGE"
         cat test
