on:
  pull_request:
    branches: 
      - main
    types: [created]

jobs:
  change-on-prod:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
       run:  echo "branch: $GITHUB_REF_NAME"
     - name: push-prod
       run: |
	   cat test
	   echo "doing something on STAGE"
