name: Push to stage
on:
  pull_request:
    branches: 
      - main
    types: [opened]
jobs:
  change-on-stage:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: push-stage
       run: |
         printenv
         echo "branch: $GITHUB_REF_NAME"
         cat test
         echo "doing something on stage"
