on:
  pull_request:
    branches: 
      - main
    types: [created]

jobs:
  change-on-stage
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: push-stage
       run: |
         echo "branch: $GITHUB_REF_NAME"
