name: Dynamic

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
env:
  ID: "SUB_"${{ github.event.inputs.environment }}
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest    
    steps:
      - name: Install Terraform
        run: echo   ${{ matrix.version }}.${{ github.event.inputs.environment }}
      - name: Install Terraform1
        run: echo $ID
