name: printenv
on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Select Domain'
        required: true
        type: choice
        options: 
          - domain1
          - domain2
          - domain3
          - dlmz
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 111
  workflow_call:      
    uses: ./.github/workflows/called.yaml
    with:
      DOMAIN: ${{ github.event.inputs.domain }}
    secrets:
      ENV: ${{ github.event.inputs.environment }}
