name: deploy on domain

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Select Domain'
        required: true
        default: 'Domain1'
        type: choice
        options:
          - domain1
          - domain2
          - domain3
          - domain4
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.5.7
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: | 
          echo "DOMAIN=${{ github.event.inputs.domain }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TFVARS_FILE=${{ github.event.inputs.environment }}.tfvars" >> $GITHUB_ENV
          echo "BACKEND_CONFIG=${{ github.event.inputs.domain }}/Backend_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - name: Terraform Init
        run: |
          cd $DOMAIN
          echo "terraform init with $BACKEND_CONFIG"
      - name: Terraform Plan
        run: echo "terraform plan"
      - name: create pull request
        run: gh pr create -B main -H $GITHUB_REF_NAME --title "Update domain=$DOMAIN environment=$ENVIRONMENT" --body 'Created by Github action' -r andrzejp12-kodekloud/team-a
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}          
