name: Dynamic

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
env:
  ID: SUB_${{ github.event.inputs.environment }}
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10]
    runs-on: ubuntu-latest    
    steps:
      - name: step1
        run: echo   ${{ matrix.version }}.${{ github.event.inputs.environment }}
      - name: Step2
        run: echo  $ID 
      - name: step3
        run: echo ${{ vars.[env.ID] }}
        #
