name: printenv
on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Select Domain'
        required: true
        type: choice
        options: 
          - domain1
          - domain2
          - domain3
          - dlmz
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{format('ID_{0}{1}', github.event.inputs.environment, github.event.inputs.domain == vars.shared_name ? '_' + vars.shared_name : '' )}}
  terraform-plan-call:
    uses: ./.github/workflows/called.yaml
    with:
      DOMAIN:  ${{ vars[format('ID_{0}{1}', github.event.inputs.environment,github.event.inputs.domain == vars.shared_name && '_shared' || '' )] }}
