name: deploy-toy-website
on: [workflow_dispatch]
    inputs:
      domain:
        description: 'Select Domain'
        required: true
        type: choice
        options: 
          - domain1
          - domain2
          - domain3
          - shared
jobs:
  ask-approve:
    runs-on: ubuntu-latest
    steps:
      - name: doing something1
        run: echo OK
      - name: Wait for approval1
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: andrzejp12
          minimum-approvals: 1
          issue-title: "doing something1"
          issue-body: "Please approve something1"
      - name: doing something2
        run: echo OK
      - name: Wait for approval2
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: andrzejp12
          minimum-approvals: 1
          issue-title: "doing something2"
          issue-body: "Please approve something2"
